info:
  contact: { }
paths:
  /auth/bindRoles:
    post:
      consumes:
        - application/json
      description: 给用户分配角色
      produces:
        - application/json
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":"ok"}'
          schema:
            type: string
      summary: 给用户分配角色
      tags:
        - 权限
  /auth/captcha:
    get:
      consumes:
        - application/json
      description: 获取验证码
      produces:
        - application/json
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":"ok"}'
          schema:
            type: string
      summary: 获取验证码
      tags:
        - 权限
  /auth/login:
    post:
      consumes:
        - application/json
      description: 登录
      produces:
        - application/json
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":"ok"}'
          schema:
            type: string
      summary: 登录
      tags:
        - 权限
  /roles:
    get:
      consumes:
        - application/json
      description: 获取角色
      produces:
        - application/json
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":"ok"}'
          schema:
            type: string
      summary: 获取角色
      tags:
        - 角色
    post:
      consumes:
        - application/json
      description: 创建角色
      produces:
        - application/json
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":"ok"}'
          schema:
            type: string
      summary: 创建角色
      tags:
        - 角色
  /roles/{id}:
    delete:
      consumes:
        - application/json
      description: 删除角色
      produces:
        - application/json
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":"ok"}'
          schema:
            type: string
      summary: 删除角色
      tags:
        - 角色
    put:
      consumes:
        - application/json
      description: 更新角色
      produces:
        - application/json
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":"ok"}'
          schema:
            type: string
      summary: 更新角色
      tags:
        - 角色
  /users:
    get:
      consumes:
        - application/json
      description: 获取系统中所有用户的列表
      parameters:
        - description: 页码，默认为1
          in: query
          name: page
          type: integer
        - description: 每页显示的用户数量，默认为10
          in: query
          name: limit
          type: integer
      produces:
        - application/json
      responses: { }
      summary: 获取用户列表
      tags:
        - 用户管理
    post:
      consumes:
        - application/json
      description: 创建新用户并将其添加到系统中
      produces:
        - application/json
      responses: { }
      summary: 创建新用户
      tags:
        - 用户管理
  /users/{id}:
    delete:
      consumes:
        - application/json
      description: 根据用户ID删除用户
      parameters:
        - description: 用户ID
          in: path
          name: id
          required: true
          type: integer
      produces:
        - application/json
      responses: { }
      summary: 删除用户
      tags:
        - 用户管理
    get:
      consumes:
        - application/json
      description: 根据ID获取用户信息
      produces:
        - application/json
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":"ok"}'
          schema:
            type: string
      summary: 根据ID获取用户信息
      tags:
        - 用户管理
    put:
      consumes:
        - application/json
      description: 更新现有用户的信息
      parameters:
        - description: 用户ID
          in: path
          name: id
          required: true
          type: integer
      produces:
        - application/json
      responses: { }
      summary: 更新用户信息
      tags:
        - 用户管理
  /users/search:
    get:
      consumes:
        - application/json
      description: 根据查询参数查询用户信息
      produces:
        - application/json
      responses: { }
      summary: 查询用户
      tags:
        - 用户管理
swagger: "2.0"
