name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Build
        run: |
          mkdir -p build
          go build -o build/your_executable ./server

      - name: Archive
        run: |
          cd build
          tar -czvf your_project_v1.0.0.tar.gz your_executable

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: your_project_v1.0.0
          path: build/your_project_v1.0.0.tar.gz
